language: python

services:
  - docker

before_install:
  - docker build -t co:latest .
  - docker ps -a

deploy:
  provider: script
  script: bash docker_push
  on:
    branch: master

# command to install dependencies
#install:
#  - pip install -r requirements.txt
# command to run tests
script:
  - nose2