version: '3'
services:
  app:
    build: .
    labels:
        - "traefik.enable=true"
        - "traefik.backend=countryservice-app"
        - "traefik.backend.healthcheck.path=/health"
        - "traefik.backend.healthcheck.interval=1s"
        - "traefik.frontend.rule=Host:0.0.0.0"
        - "traefik.port=5001"
    networks:
        - traefik
        
networks:
    traefik:
        external:
            name: traefik_webgateway
