version: '3'
services:
  web:
    build: .
    labels:
        - "traefik.enable=true"
        - "traefik.backend=countryservice-app"
        - "traefik.backend.healthcheck.path=/health"
        - "traefik.backend.healthcheck.interval=1s"
        - "traefik.frontend.rule=Host:localhost"
        - "traefik.port=5001"
    networks:
        - traefik
    ports:
      - "5001:5001"
networks:
    traefik:
        external:
            name: traefik_webgateway
